version: '3.4'

services:
  catalog.db:
    image: ${DOCKER_REGISTRY-}mongo

  catalog.webapi:
    image: ${DOCKER_REGISTRY-}catalogwebapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.WebApi/Dockerfile

    depends_on:
      - catalog.db
